import { normalize } from 'path';
import PostBody from './components/post-body';

export default {
    layout: {
        container: {
            maxWidth: '760px',
            minHeight: '100vh',
            margin: '0 auto',
            px: 3,
            py: 0,
        },
    },
    breakpoints: ['40em', '52em', '64em'],
    space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
    fonts: {
        body:
            'Campton, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif',
        heading: 'inherit',
        monospace: 'Menlo, monospace',
    },
    fontSizes: [16, 18, 21, 26, 32, 44, 64, 72, 96],
    fontWeights: {
        body: 400,
        heading: 600,
        light: 300,
        medium: 500,
        semiBold: 600,
        bold: 700,
        extraBold: 800,
        black: 900,
    },
    lineHeights: {
        body: 1.6,
        heading: 1.125,
    },
    colors: {
        background: 'rgb(255, 255, 255)',
        text: 'rgba(0,0,0,0.85)',
        darkerGray: 'rgba(0,0,0,0.65)',
        darkGray: 'rgba(0,0,0,0.50)',
        lightGray: 'rgba(0,0,0,0.35)',
        lightestGray: 'rgba(0,0,0,0.15)',
        primary: '#07c',
        secondary: '#30c',
        muted: '#f6f6f6',
    },
    buttons: {
        primary: {
            fontSize: 0,
            lineHeight: 'body',
            color: 'darkerGray',
            bg: 'background',
            border: '1px solid',
            borderColor: 'lightGray',
            textDecoration: 'none',
            cursor: 'pointer',
            fontWeight: 'body',
            fontStyle: 'normal',
            py: 0,
            px: 3,
            '&:hover': {
                borderColor: 'text',
                color: 'text',
            },
        },
    },
    images: {
        avatar: {
            width: 48,
            height: 48,
            borderRadius: 99999,
        },
    },
    links: {
        bold: {
            fontWeight: 'bold',
        },
        nav: {
            fontSize: 0,
            fontWeight: 'medium',
            color: 'inherit',
            textDecoration: 'none',
            border: '1px',
        },
    },
    text: {
        title: {
            fontFamily: 'heading',
            lineHeight: 'heading',
            fontWeight: 'heading',
            letterSpacing: '-0.025em',
            fontSize: 4,
            pt: 4,
            pb: 2,
        },
        subHeading: {
            fontFamily: 'heading',
            fontSize: 3,
            lineHeight: 'heading',
            fontWeight: 'medium',
            letterSpacing: '-0.025em',
            borderBottom: '1px solid',
            borderColor: 'lightestGray',
            pb: 3,
        },
        postTitle: {
            color: 'rgba(41, 41, 41)',
            fontFamily: 'heading',
            lineHeight: '60px',
            fontWeight: '500',
            letterSpacing: '-0.025em',
            fontSize: 5,
            p: 0,
            mx: 0,
            my: 4,
        },
    },
    styles: {
        root: {
            fontSize: 2,
            lineHeight: 'body',
            fontFamily: 'body',
            fontWeight: 'body',
        },
        p: {
            fontSize: 2,
            fontFamily: 'body',
            fontWeight: 'body',
            lineHeight: 'body',
            color: 'rgb(41,41,41)',
            m: 0,
            p: 0,
            pt: 4,
        },
        h1: {
            variant: 'text.heading',
            lineHeight: 'heading',
            fontWeight: 'heading',
            fontSize: 4,
            m: 0,
            p: 0,
            pt: 5,
        },
        h2: {
            variant: 'text.heading',
            lineHeight: 'heading',
            fontWeight: 'heading',
            fontSize: 3,
            m: 0,
            p: 0,
            pt: 5,
        },
        h3: {
            variant: 'text.heading',
            lineHeight: 'heading',
            fontWeight: 'medium',
            fontSize: 3,
            color: 'rgba(41,41,41, 0.95)',
            m: 0,
            p: 0,
            pt: 5,
        },
        h4: {
            variant: 'text.heading',
            fontSize: 2,
            fontWeight: 'extraBold',
            m: 0,
            p: 0,
            pt: 4,
        },
        h5: {
            variant: 'text.heading',
            fontSize: 2,
            fontWeight: 'bold',
            m: 0,
            p: 0,
            pt: 4,
        },
        h6: {
            variant: 'text.heading',
            fontSize: 0,
            fontWeight: 'bold',
            m: 0,
            p: 0,
            mt: 4,
        },
        hr: {
            m: 0,
            p: 0,
            my: 4,
        },
        strong: {
            fontWeight: 'semiBold',
        },
        blockquote: {
            m: 0,
            p: 0,
            mt: 4,
            fontStyle: 'italic',
            letterSpacing: '-0.003em',
            borderLeft: '3px solid',
            borderColor: 'body',
            pl: 3,
            ml: '-16px',
            // @ts-ignore
            p: {
                p: 0,
                m: 0,
            },
        },
        pre: {
            fontFamily: 'monospace',
            overflowX: 'auto',
            bg: 'rgba(90, 90, 90, 0.15)',
            px: 2,
            py: 1,
            borderRadius: '5px',
            code: {
                fontSize: 1,
                color: 'inherit',
                bg: 'transparent',
            },
        },
        code: {
            fontSize: 1,
            fontFamily: 'monospace',
            bg: 'rgba(90, 90, 90, 0.15)',
            px: 2,
            py: 1,
            borderRadius: '5px',
        },
        a: {
            color: 'rgb(41,41,41)',
            textDecoration: 'none',
            borderBottom: '1px solid',
            borderColor: 'rgba(41, 41, 41, 0.5)',
        },
        table: {
            width: '100%',
            borderCollapse: 'separate',
            borderSpacing: 0,
        },
        th: {
            textAlign: 'left',
            borderBottomStyle: 'solid',
        },
        td: {
            textAlign: 'left',
            borderBottomStyle: 'solid',
        },
    },
};
